service: freitag-crawler

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 30
  region: ap-northeast-2

custom:
  secrets: ${file(.secrets.yml):prod}

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  freitag:
    handler: src/main.handleAsync
    environment:
      FIREBASE_API_KEY: ${self:custom.secrets.FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${self:custom.secrets.FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${self:custom.secrets.FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${self:custom.secrets.FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${self:custom.secrets.FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${self:custom.secrets.FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${self:custom.secrets.FIREBASE_MEASUREMENT_ID}
      DISCORD_BOT_TOKEN: ${self:custom.secrets.DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${self:custom.secrets.DISCORD_CHANNEL_ID}
    events:
      - schedule:
        rate: rate(2 minute)
