service: freitag-crawl-project-3

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  region: ap-northeast-2

custom:
  secrets: ${file(.secrets.yml):prod}

package:
  patterns:
    - '!node_modules/puppeteer/.local-chromium/**'

functions:
  # fretiag:
  #   handler: build/src/main.handleAsync
  #   timeout: 15
  #   environment:
  #     FIREBASE_API_KEY: ${self:custom.secrets.FIREBASE_API_KEY}
  #     FIREBASE_AUTH_DOMAIN: ${self:custom.secrets.FIREBASE_AUTH_DOMAIN}
  #     FIREBASE_PROJECT_ID: ${self:custom.secrets.FIREBASE_PROJECT_ID}
  #     FIREBASE_STORAGE_BUCKET: ${self:custom.secrets.FIREBASE_STORAGE_BUCKET}
  #     FIREBASE_MESSAGING_SENDER_ID: ${self:custom.secrets.FIREBASE_MESSAGING_SENDER_ID}
  #     FIREBASE_APP_ID: ${self:custom.secrets.FIREBASE_APP_ID}
  #     FIREBASE_MEASUREMENT_ID: ${self:custom.secrets.FIREBASE_MEASUREMENT_ID}
  #     DISCORD_BOT_TOKEN_LASSIE: ${self:custom.secrets.DISCORD_BOT_TOKEN}
  #     DISCORD_CHANNEL_ID: ${self:custom.secrets.DISCORD_CHANNEL_ID}
  #   events:
  #     - schedule:
  #         rate: rate(2 minutes)
  #         enabled: true
  lassie:
    handler: build/src/main.getLassie
    timeout: 120
    environment:
      FIREBASE_API_KEY: ${self:custom.secrets.FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${self:custom.secrets.FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${self:custom.secrets.FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${self:custom.secrets.FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${self:custom.secrets.FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${self:custom.secrets.FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${self:custom.secrets.FIREBASE_MEASUREMENT_ID}
      DISCORD_BOT_TOKEN_LASSIE: ${self:custom.secrets.DISCORD_BOT_TOKEN_LASSIE}
      DISCORD_CHANNEL_ID: ${self:custom.secrets.DISCORD_CHANNEL_ID}
      DATADOM_COOKIES:
      MY_ID: byseop@gmail.com
      MY_PW: skeowlak12!@
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
  dexter:
    handler: build/src/main.getDexter
    timeout: 120
    environment:
      FIREBASE_API_KEY: ${self:custom.secrets.FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${self:custom.secrets.FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${self:custom.secrets.FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${self:custom.secrets.FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${self:custom.secrets.FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${self:custom.secrets.FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${self:custom.secrets.FIREBASE_MEASUREMENT_ID}
      DISCORD_BOT_TOKEN_DEXTER: ${self:custom.secrets.DISCORD_BOT_TOKEN_DEXTER}
      DISCORD_CHANNEL_ID: ${self:custom.secrets.DISCORD_CHANNEL_ID}
      DATADOM_COOKIES:
      MY_ID: byseop@gmail.com
      MY_PW: skeowlak12!@
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
  jamie:
    handler: build/src/main.getJamie
    timeout: 120
    environment:
      FIREBASE_API_KEY: ${self:custom.secrets.FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${self:custom.secrets.FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${self:custom.secrets.FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${self:custom.secrets.FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${self:custom.secrets.FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${self:custom.secrets.FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${self:custom.secrets.FIREBASE_MEASUREMENT_ID}
      DISCORD_BOT_TOKEN_JAMIE: ${self:custom.secrets.DISCORD_BOT_TOKEN_JAMIE}
      DISCORD_CHANNEL_ID: ${self:custom.secrets.DISCORD_CHANNEL_ID}
      DATADOM_COOKIES:
      MY_ID: byseop@gmail.com
      MY_PW: skeowlak12!@
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
  hawaiifiveo:
    handler: build/src/main.getHawaiiFiveO
    timeout: 120
    environment:
      FIREBASE_API_KEY: ${self:custom.secrets.FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${self:custom.secrets.FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${self:custom.secrets.FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${self:custom.secrets.FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${self:custom.secrets.FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${self:custom.secrets.FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${self:custom.secrets.FIREBASE_MEASUREMENT_ID}
      DISCORD_BOT_TOKEN_HAWAIIFIVEO: ${self:custom.secrets.DISCORD_BOT_TOKEN_HAWAIIFIVEO}
      DISCORD_CHANNEL_ID: ${self:custom.secrets.DISCORD_CHANNEL_ID}
      DATADOM_COOKIES:
      MY_ID: ${self:custom.secrets.MY_ID}
      MY_PW: ${self:custom.secrets.MY_PW}
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true

configValidationMode: error
